name: Convert Markdown to HTML
on:
  push:
    branches:
      - main  # Runs only on pushes to the main branch (optional, adjust as needed)
  pull_request:  # Runs on PRs too, useful for previewing changes
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install marked  # Ensures `marked` is available

      - name: Convert Markdown to HTML
        run: node convert.js  # Runs your conversion script

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.html
          git diff --staged --quiet || (git commit -m "Auto-converted Markdown to HTML" && git push)
